# Generated by Django 6.0.4 on 2026-04-16 23:17

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0008_alter_resumetemplate_html_structure'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resume.resumetemplate',),
        ),
    ]
