# Generated by Django 6.0.4 on 2026-04-28 21:26

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0002_resumetemplate_alter_resume_options_and_more'),
        ('templates', '0001_add_thomas_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('resume.resumetemplate',),
        ),
    ]
