# Generated by Django 5.2.17 on 2026-09-29 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=100, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('processed', models.BooleanField(default=False)),
                ('error', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_code', models.CharField(max_length=40)),
                ('amount', models.PositiveIntegerField(help_text='Amount in currency subunits (paise for INR).')),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('credits', models.PositiveIntegerField(default=0)),
                ('premium_days', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='CREATED', max_length=12)),
                ('receipt', models.CharField(max_length=40, unique=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('signature_verified', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PremiumSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=12)),
                ('started_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('source_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activated_subscriptions', to='billing.paymentorder')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='premium_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
