# Generated by Django 6.0.4 on 2026-05-07 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumeanalysis',
            name='analysis_data',
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='ats_breakdown',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='contact_issues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='format_issues',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='keyword_analysis',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='matched_skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='missing_sections',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='missing_skills',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='suggestions',
            field=models.JSONField(default=list),
        ),
    ]
