# Generated by Django 5.2.17 on 2026-09-27 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_missing_credit_accounts(apps, schema_editor):
    User = apps.get_model("users", "User")
    Account = apps.get_model("ai", "AICreditAccount")
    batch = []
    for user_id in User.objects.values_list("pk", flat=True).iterator(chunk_size=1000):
        batch.append(Account(user_id=user_id))
        if len(batch) == 1000:
            Account.objects.bulk_create(batch, ignore_conflicts=True)
            batch = []
    if batch:
        Account.objects.bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('users', '0011_account_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aicredittransaction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_credit_adjustments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_missing_credit_accounts, migrations.RunPython.noop),
    ]
