# Generated by Django 6.0.3 on 2026-04-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('modern', 'The Professional'), ('classic', 'Tech Savvy'), ('minimal', 'Pure Minimal')], max_length=20),
        ),
    ]
