# Generated by Django 6.0.4 on 2026-04-28 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(default='general', max_length=60)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='templates/previews/')),
                ('html_structure', models.TextField()),
                ('css', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RenameField(
            model_name='resume',
            old_name='content',
            new_name='data',
        ),
        migrations.AddField(
            model_name='resume',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/pdfs/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resume.resumetemplate'),
        ),
    ]
