# Generated by Django 6.0.3 on 2026-04-05 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resume_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.CharField(choices=[('The Professional', ' modern'), (' Tech Savvy', 'classic'), (' Pure Minimal', 'minimal')], max_length=20),
        ),
    ]
