# Generated by Django 5.2.17 on 2026-09-19 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_optimizer', '0002_optimizationsession_final_analysis_json_and_more'),
        ('resume', '0004_add_thomas_themes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='resumes/versions/')),
                ('optimization_session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='optimized_version', to='job_optimizer.optimizationsession')),
                ('source_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resume.resume')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resume.resumetemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
