# Generated by Django 6.0.4 on 2026-04-16 23:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


def map_legacy_template_values(apps, schema_editor):
    Resume = apps.get_model('resume', 'Resume')
    ResumeTemplate = apps.get_model('resume', 'ResumeTemplate')

    template_codes = {
        'modern': 'Modern',
        'classic': 'Classic',
        'minimal': 'Minimal',
    }

    created_templates = {}
    for code, display_name in template_codes.items():
        template = ResumeTemplate.objects.create(
            name=display_name,
            schema={},
            preview_image=None,
            is_active=True,
        )
        created_templates[code] = template.id.hex

    fallback_template = ResumeTemplate.objects.create(
        name='Default',
        schema={},
        preview_image=None,
        is_active=True,
    )

    for resume in Resume.objects.all().only('id', 'template'):
        mapped_template_id = created_templates.get(resume.template, fallback_template.id.hex)
        Resume.objects.filter(pk=resume.pk).update(template=mapped_template_id)


def reverse_map_legacy_template_values(apps, schema_editor):
    ResumeTemplate = apps.get_model('resume', 'ResumeTemplate')
    ResumeTemplate.objects.filter(name__in=['Modern', 'Classic', 'Minimal', 'Default']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_alter_resume_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('schema', models.JSONField()),
                ('preview_image', models.URLField(blank=True, max_length=1024, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'ordering': ['-updated_at']},
        ),
        migrations.RunPython(map_legacy_template_values, reverse_map_legacy_template_values),
        migrations.RenameField(
            model_name='resume',
            old_name='content',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='resume',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='resume',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resume',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resume.resumetemplate'),
        ),
    ]
