# Generated by Django 6.0.4 on 2026-04-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_rename_schema_to_html_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumetemplate',
            name='html_structure',
            field=models.TextField(),
        ),
    ]
