# Generated by Django 6.0.4 on 2026-04-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_refactor_vikash_template_structure'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/pdfs/'),
        ),
        migrations.AddField(
            model_name='resume',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/thumbnails/'),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='category',
            field=models.CharField(default='general', max_length=60),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='css',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
