# Generated by Django 5.2.17 on 2026-09-18 22:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0004_add_thomas_themes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_descriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_resume_version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ANALYZING', 'Analyzing'), ('ANALYZED', 'Analyzed'), ('MATCHING', 'Matching'), ('READY_FOR_REVIEW', 'Ready for Review'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='DRAFT', max_length=30)),
                ('analysis_json', models.JSONField(blank=True, default=dict)),
                ('match_results_json', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('job_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_sessions', to='job_optimizer.jobdescription')),
                ('source_resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_sessions', to='resume.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationSuggestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suggestion_type', models.CharField(choices=[('SUMMARY_REWRITE', 'Summary Rewrite'), ('EXPERIENCE_REWRITE', 'Experience Rewrite'), ('PROJECT_REWRITE', 'Project Rewrite'), ('SKILL_EMPHASIS', 'Skill Emphasis'), ('SKILL_REORDER', 'Skill Reorder'), ('KEYWORD_ALIGNMENT', 'Keyword Alignment'), ('CLARITY', 'Clarity'), ('CONCISENESS', 'Conciseness'), ('ATS_FORMATTING', 'ATS Formatting'), ('MISSING_EVIDENCE', 'Missing Evidence')], max_length=40)),
                ('resume_path', models.CharField(max_length=255)),
                ('original_value', models.TextField(blank=True, default='')),
                ('ai_suggestion', models.TextField(blank=True, default='')),
                ('user_edited_value', models.TextField(blank=True, null=True)),
                ('final_value', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EDITED', 'Edited')], db_index=True, default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True, default='')),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('evidence_reference', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(default='HIGH', max_length=20)),
                ('optimization_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='job_optimizer.optimizationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
