# Generated by Django 5.2.17 on 2026-09-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationsession',
            name='final_analysis_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='optimizationsession',
            name='source_data_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='optimizationsuggestion',
            name='prompt_version',
            field=models.CharField(default='resume_optimizer_v1', max_length=40),
        ),
        migrations.AddField(
            model_name='optimizationsuggestion',
            name='revision_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='optimizationsuggestion',
            name='suggestion_type',
            field=models.CharField(choices=[('SUMMARY_IMPROVEMENT', 'Summary Improvement'), ('EXPERIENCE_BULLET_IMPROVEMENT', 'Experience Bullet Improvement'), ('PROJECT_BULLET_IMPROVEMENT', 'Project Bullet Improvement'), ('SUMMARY_REWRITE', 'Summary Rewrite'), ('EXPERIENCE_REWRITE', 'Experience Rewrite'), ('PROJECT_REWRITE', 'Project Rewrite'), ('SKILL_EMPHASIS', 'Skill Emphasis'), ('SKILL_REORDER', 'Skill Reorder'), ('KEYWORD_ALIGNMENT', 'Keyword Alignment'), ('CLARITY', 'Clarity'), ('CONCISENESS', 'Conciseness'), ('ATS_FORMATTING', 'ATS Formatting'), ('MISSING_EVIDENCE', 'Missing Evidence')], max_length=40),
        ),
    ]
