# Generated by Django 5.2.1 on 2026-09-08 11:03

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def normalize_existing_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    users = User.objects.using(schema_editor.connection.alias)
    seen = set()
    for email in users.values_list('email', flat=True).iterator():
        normalized = email.strip().lower()
        if not normalized or normalized in seen:
            raise RuntimeError('Conflicting normalized user emails: resolve identity conflicts before retrying migration. No accounts were merged or deleted.')
        seen.add(normalized)
    # Transactional on PostgreSQL: uniqueness errors roll back the entire migration.
    for user in users.all().iterator():
        users.filter(pk=user.pk).update(email=user.email.strip().lower(), username=user.email.strip().lower(), created_at=user.date_joined)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=128)),
                ('purpose', models.CharField(choices=[('EMAIL_VERIFICATION', 'Email verification'), ('PASSWORD_RESET', 'Password reset')], max_length=24)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.RunPython(normalize_existing_users, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='users_email_ci_unique'),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_otps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['user', 'purpose', '-created_at'], name='users_otp_lookup'),
        ),
        migrations.AddConstraint(
            model_name='emailotp',
            constraint=models.UniqueConstraint(condition=models.Q(('is_used', False)), fields=('user', 'purpose'), name='users_one_active_otp'),
        ),
    ]
