# Generated by Django 5.2.17 on 2026-09-27 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_mobile_otp_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpchallenge',
            name='action',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='otpchallenge',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_otp_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='otpchallenge',
            name='purpose',
            field=models.CharField(choices=[('authentication', 'Authentication'), ('change_phone', 'Change phone'), ('account_recovery', 'Account recovery'), ('account_action', 'Account action')], default='authentication', max_length=32),
        ),
    ]
