# Generated by Django 6.0.4 on 2026-04-16 23:17

import users.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_full_name_to_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
